# Generated by Django 4.0.4 on 2022-05-27 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('timestampzone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.timestampzone')),
                ('email', models.CharField(max_length=200, unique=True)),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=200)),
                ('refreshtoken', models.CharField(max_length=200)),
                ('deleted_at', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
            },
            bases=('utils.timestampzone',),
        ),
    ]
