# Generated by Django 4.0.4 on 2022-06-01 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0004_alter_timestampzone_deleted_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('timestampzone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.timestampzone')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.CharField(max_length=200, unique=True)),
                ('nickname', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=200)),
                ('refreshtoken', models.CharField(max_length=200)),
                ('deleted_at', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
            bases=('utils.timestampzone', models.Model),
        ),
    ]
