# Generated by Django 4.0.4 on 2022-06-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='refreshtoken',
            field=models.TextField(),
        ),
    ]
