# Generated by Django 4.0.4 on 2022-06-05 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
        ('utils', '0004_alter_timestampzone_deleted_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('timestampzone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.timestampzone')),
                ('quantity', models.IntegerField()),
                ('product_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'carts',
            },
            bases=('utils.timestampzone',),
        ),
    ]
