# Generated by Django 4.0.4 on 2022-05-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timestampzone',
            name='deleted_time',
            field=models.DateTimeField(default=False),
        ),
    ]
