# Generated by Django 4.0.4 on 2022-05-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_alter_timestampzone_deleted_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timestampzone',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
