# Generated by Django 4.0.4 on 2022-05-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_alter_timestampzone_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timestampzone',
            name='deleted_time',
            field=models.DateTimeField(null=True),
        ),
    ]
